---
output: 
  rticles::ctex:
  ## pdf_document:
    keep_tex: yes
    template: svm-latex-cv.tex
geometry: margin=1in

chinese: TRUE

title: "CV"
author: Yuehong Cassandra Tai

#jobtitle: "Assistant Research Professor,The Center for Social Data Analytics"
address: "425 Susan Welch Liberal Arts Building, Pennsylvania State University, University Park, PA 16802"
fontawesome: yes
email: yhcasstai@psu.edu
github: Tyhcass
web: cassyuehtai.netlify.app
updated: false
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10.5pt
linkcolor: blue
urlcolor: blue
---

```{r setup, include=FALSE}

```

# ACADEMIC APPOINTMENTS

* Pennsylvania State University
  - Assistant Research Professor, Center for Social Data Analytics \hfill 2025-
  - Assistant Director, Center for Social Data Analytics
  - Postdoctoral Scholar, Center for Social Data Analytics \hfill 2022-2024

# EDUCATION 
* __Ph.D.__ Program in Political Science, University of Iowa, U.S.A. \hfill 2017-2022
   - Fields: Comparative Politics, Political Methodology, American Politics
* __MSc__ in International Political Economy, Nanyang Technological University, Singapore \hfill 2008
* __LL.B.__ in Diplomacy, Renmin University of China, China \hfill 2007

# RESEARCH AREAS
* __Political Science__ 
  - Responsible AI in Governance, Political Communication, Public Opinion, Chinese Politics.
  
* __Computational Social Science__ 
  - GenAI Pipelines and Evaluation, LLMs/ NLP/ Text-as-data, Bayesian Measurement Models, Applied Statistical Methods.
  
# PUBLICATIONS

* __AI and Computational Social Science__
  - 13.Tai, Yuehong Cassandra, Yu-Ru Lin, and Bruce A. Desmarais. 2025. “Public Oﬀicials’ Online Sharing of
Misinformation: Institutional and Ideological Checks.”  *Conditionally Accepted at Political Communication*.
  - 12.Tai, Yuehong Cassandra, Nitheesha Nakka, Khushi Navin Patni, Sarah Rajtmajer, Kevin Munger, Yu-Ru Lin, and Bruce A. Desmarais. 2025. “The Digitally Accountable Public Representation Database: Measuring Online Communication by Federal, State, and Local Oﬀicials.”   *Accepted at Scientific Data*.
  - 11.Tai, Yuehong Cassandra, Khushi Navin Patni, Nicholas Daniel Hemauer, Bruce A. Desmarais, and Yu-Ru Lin. 2025. “GenAI vs. Human Fact-Checkers: Accurate Ratings, Flawed Rationales.” In *Proceedings of the 17th ACM Web Science Conference 2025*.
   - 10.Nakka, Nitheesha, Issac Pollert, Lingyu Fuca, and Yuehong Cassandra Tai. 2025. “Navigating Hate and
Anti-Hate Speech: Bridging Large Language Model and Human Expertise in Public Oﬀicials’ Online
Communication.” [__with graduate students__] *Accepted at CySoc 2025 International Workshop on Cyber Social Threats.*
  - 9.Biswas, Ahana, Yu-Ru Lin, Yuehong Cassandra Tai and Bruce A. Desmarais. 2025. “Political Elites in the
Attention Economy: Visibility Over Civility and Credibility?” In *Proceedings of the International AAAI Conference on Web and Social Media.*
  - 8.Tai, Yuehong Cassandra, Roan Buma and Bruce A. Desmarais. 2023. “Oﬀicial Yet Questionable: Examining Misinformation in U.S. State Legislators’ Tweets.” *Journal of Information Technology & Politics*.

* __Public Opinion and Measurement__
  - 7.Tai, Yuehong Cassandra. 2025. “The Upsides and Downsides of Generalized Trust: The Mediating Effect of
  Democratic Institutions.” *International Journal of Public Opinion Research*.
  - 6.Hu, Yue, Yuehong Cassandra Tai, Hyein Ko, Byung-Deuk Woo, and Frederick Solt. 2025. “An Incomplete Recipe: One-Dimensional Latent Variables Do Not Capture the Full Flavor of Democratic Support.” *Research & Politics*.
  - 5.Woo, Byung-Deuk, Hyein Ko, Yuehong Cassandra Tai, Yue Hu, and Frederick Solt. 2024. “Public Support for Gay Rights Across Countries and Over Time.” *Social Science Quarterly*.
  - 4.Hu, Yue, Yuehong Cassandra Tai\*, and Frederick Solt. 2024. “Revisiting the Evidence on Thermostatic Response to Democratic Change: Degrees of Democratic Support or Researcher Degrees of Freedom?” *Political Science Research and Methods*. [\* __co-first author__]
  - 3.Tai, Yuehong Cassandra, Yue Hu, and Frederick Solt. 2022. “Democracy, Public Support, and Measurement Uncertainty” *American Political Science Review*.

* __Chinese Politics__
  - 2.Tai, Yuehong Cassandra, Jielu Yao and Elise Pizzi. 2022. “Policy Adoption and Diffusion during the
COVID-19 Crisis” *Journal of Asian Public Policy*.
  - 1.Tai, Yuehong Cassandra. 2022. “Determinants of Chinese Provinces’ Responses to the 2018 Vaccine
Scandal: Policy Orientation and Neighboring Effect” *Asian Survey*.

# WORKS IN PROGRESS
* __Under Review__
  - Yu, Dong Erico, and Yuehong Cassandra Tai. “Speak ‘As Good As Men’? An Empirical Study of Gender
Variation in Chinese Courtroom Audio” [__Revise & Resubmit__]
  - Tai, Yuehong Cassandra. “Comparative Estimates of Public Trust in Government Across 115 Countries, 1973–2020” [__Revise & Resubmit__]
  - Tai, Yuehong Cassandra and Frederick Solt. “Trust in Civil Servants: A Cross-National Dataset for Public Policy Research, 1986–2022”
  - Kim, Yooneui and Yuehong Cassandra Tai. “The Skeptical Public: Trust in the United Nations” 
  - Hu, Yue, Yuehong Cassandra Tai, and Frederick Solt. “Data Wrangling Before Harmonization: Best Practices for Getting Past the ‘Janitor Work.’” 
  - Ma, Haofeng, Jeongho Choi, Yuehong Cassandra Tai, Yue Hu, and Frederick Solt. “Macrodiscontent Across Countries”

* __Working Paper__
  - *AI and Computational Social Science*
   - "Who Speaks for AI? Local News Papers and AI Policy News Frames" (with Hyein Ko)
   - "From Annotation to Oversight: A Pipeline Approach to GenAI Evaluation" (with Hyein Ko and Nora Webb Williams) 
   - “Understanding Asian Hate in State Legislatures: An Electoral Connection” (with Issac Michael
Pollert, Nitheesha Nakka, and Lingyu Jack Fuca) [__Lead Author__]
   - “Who Speaks, Who Falls Silent: Strategic Climate Messaging by State Legislators on Facebook and X” (with Xun Cao, Yu-Ru Lin and Bruce A. Desmarais) [__Lead Author__]
   - “Large Language Models in Social Science: A Literature Review of LLMs and GenAI in Political Science and Communication” (with Pooja Iyer)
  - *Public Opinion*
   + “How Does Public Opinion Affect Climate Change Policies?” (with Xun Cao and Fred Solt) [__Lead Author__]
   + “Surfing Waves or Making Waves? Declining Trust in Democracy and Election of Personalist Leaders” (with Jia Li and M. Rosemary Pang) 
   + “Dynamic Trust and States’ Failure in Public Health: Evidence from a Global Time Series Data”
     
# CONFERENCE PRESENTATIONS

- “Who Speaks, Who Falls Silent: Strategic Climate Messaging by State Legislators on Facebook and X”
  - PolNet-PaCSS 2025, Harvard University, MA \hfill Aug 2025
  - PolMeth 2025, Emory University, GA \hfill July 2025
- “State Legislators’ Misinformation and the Limits of LLMs’ Evaluative Reasoning”
  - Information and Misinformation in Elections, California Institute of Technology, CA \hfill Jan 2025
- “The Digitally Accountable Public Representation Database: Measuring Online Communication by Federal, State, and Local Oﬀicials”
  - (Large) Language Models in Social Science 2024, University of Pennsylvania, PA \hfill Sep 2024
  - PolMeth 2024, University of California, CA \hfill July 2024
- “Climate Clash: Fossil Fuel Influence, Public Opinion, and State Legislators’ Online Discourse”
  - APSA 2024, University of Pennsylvania, PA \hfill Sep 2024
  - Visions in Methodology 2024, Washington University in St.Louis, MO \hfill May 2024
- “Understanding Asian Hate in State Legislatures: An Electoral Connection”
  - State Politics and Policy Conference 2024, University of Virginia, VA \hfill June 2024
  
- “The Prevalence of Misinformation in U.S. State Legislators’ Facebook Posts”
  - American Political Science Association Conference 2023, LA \hfill Sep 2023
  
- “Dynamic Trust and States’ Failure in Public Health: Evidence from Global Time Series Data”
  - American Political Science Association Conference 2023, LA \hfill Aug 2023

- “The Prevalence of Misinformation in U.S. State Legislators’ Facebook Posts”
  - State Politics and Policy Conference 2023, University of Pittsburgh, PA \hfill May 2023

- “How Does Public Opinion Affect Climate Change Policies? Constructing Measures of Climate Change Public Concern and Testing Their Effects on Policy Outputs”
  - Political Economy and International Relation Workshop, PSU \hfill Mar 2023

- “The Upsides and Downsides of Generalized Trust: The Mediating Effect of Democratic Institutions and
Trust in Implementing Institutions”
  - Southern Political Science Association Conference \hfill Jan 2023
- “Democracy, Public Support, and Measurement Uncertainty”
  - C-SoDA Brownbag Series \hfill Oct 2022
- “Examining States’ Public Health Failures by Measuring Trust Cross Countries and Over Time”
  - C-SoDA Kickoff Poster Presentation \hfill Sep 2022
- “Dynamic Trust and States’ Failure in Public Health: Evidence from a Global Time Series Data” 
  - Midwest Political Science Association Conference \hfill Apr 2022
  - Iowa Women Studying Politics (IWSP) Conference \hfill Feb 2022
- “Policy Burden, Issue Salience, and COVID-19 Policy Adoption in China” 
  - APSA Chinese Politics Mini-Conference \hfill Oct 2021
- “Democracy, Public Support, and Measurement Uncertainty” 
  - Joint Quantitative Political Science Conference for Asia and Australasia \hfill Jan 2021
- “Policy Orientation and Diffusion in Responsive Governance: Responses to the Chinese 2018 Vaccine
Scandal.”
  - Association of Chinese Political Studies Annual Meeting \hfill Nov 2020
- “Who is Influencing Public Opinion during a Public Health Crisis on Social Media in China?”
  - Southern Political Science Association Conference  \hfill  Jan 2020

# TEACHING EXPERIENCE
* __Method Courses__
  - __Instructor, Penn State University__
   - C-SoDA Research Practicum: AI and Governance (Undergraduate Level) \hfill Fall 2025
  - __Instructor, Penn State University__
   - PLSC 10: Scientific Study of Politics (Undergraduate Level) \hfill Fall 2024
  - Instructor, Penn State University
   - PLSC 308: Introduction to Political Research (Undergraduate Level) \hfill Spring 2024
  - Instructor, Penn State University
   - SoDA 308: Research Design for Social Data Analytics (Undergraduate Level) \hfill Fall 2023
  - __Independent Instructor, University of Iowa__
   - Hawkeye Poll (Undergraduate Level) \hfill Spring 2022
    - Guided students to design survey questions on both national and local politics, carry out telephone interviews,analyze and interpret data, and write release press and analytical papers.
  - __Teaching Assistant, University of Michigan__
   - Bayesian Modeling for the Social Sciences II: Advanced Topics, ICPSR Program, \hfill Summer 2021
    - Graded students’ assignments with detailed comments and offered one-on-one consultations on students’ individual projects.

* __Invited Talk and Guest Lecture__
  - __Guest Speaker, Penn State University__
   - The Institute for Computational and Data Sciences (ICDS) Symposium (Scheduled)  \hfill Fall 2025
     - Evaluating and Applying AI Models for Social and Political Research
  - __Guest Speaker, Penn State University__
   - Social Science Research Institute Open House (Scheduled)  \hfill Fall 2025
     - Hands-On with AI: Evaluating and Applying Models for Social Science Data
  - __Guest Speaker, Penn State University__
   - Social Science Research Institute Open House (Open to Faculty Members in SSRI) \hfill Spring 2025
     - How to Navigate High Performance Computing
  - __Guest Lecturer, Penn State University__
   - Approaches and Issues in Big Social Data (Graduate Level) \hfill Spring 2025
     - GenAI vs. Human Fact-Checkers: Accurate Ratings, Flawed Rationales
  - __Guest Lecturer, University of Massachusetts Amherst__
   - Data Analytics and Computational Social Science (Graduate Level) \hfill Fall 2024
     - LLMs in social science
  - __Guest Speaker, Xi'an Jiaotong University, China__
   - Summer Speaker Series (Graduate Level) \hfill Summer 2023
     - Latent Variable Measurements
  - __Guest Lecturer, Penn State University__
   - Approaches and Issues in Big Social Data (Graduate Level) \hfill Spring 2023
     - Measurement
  - __Guest Lecturer, University of Iowa__
   - Advanced Methods Seminar (Graduate Level) \hfill Fall 2021
     - Machine Learning
   - Analyzing Political Data (Undergraduate Level) \hfill Spring 2021
     - P-Value & Multiple Regression
   - Public Opinion
     - Public Opinion and Democracy \hfill Fall 2021
   - National Security Policy  
     - Cyber Security  \hfill March 2020 
  - __Workshop, East China Normal University, Shanghai__
   - Introduction to Python (Graduate Level) \hfill Dec 2020
     - Web scraping, social media data wrangling and analysis
  
* __Comparative Politics and American Politics Courses__
   - Teaching Assistant, University of Iowa
     - Introduction to Political Behavior   \hfill Fall 2019
     - Introduction to Comparative Politics  \hfill Fall 2018, Spring 2019
     - The Presidency    \hfill Fall 2017
     - Introduction to Comparative Politics (Online Course) \hfill Summer 2018, 2019

# EXTERNAL AND CAMPUS SERVICE
  - __Member__: American Political Science Association (sections on Political Methodology), the Midwestern
Political Science Association and Association of Chinese Political Science
  - __Reviewer__: American Political Science Review, American Journal of Political Science, British Journal of Political Science, Research and Politics, The International Conference on Weblogs and Social Media (ICWSM), International World Wide Web Conference 2025 (WWW2025), Public Opinion Quarterly, Asian Survey, International Journal of Public Opinion Research, International Journal of Comparative Sociology.
  - __POLMETH Mailing List Editor__: The Society for Political Methodology. \hfill 2024 -
  - __Seed Grant Reviewer__: Center for Social Data Analytics. Pennsylvania State University \hfill 2022, 2023,2024,2025
  - __Planning Committee Member__: 16th Postdoctoral Research Symposium. Pennsylvania State University \hfill2023
  - __Committee Member__: Postdoctoral Scholar Committee. College of the Liberal Arts, Pennsylvania State University \hfill 2022
  - __iPeer Mentor__: iPeer Mentorship Program. International Student and Scholar Services, University of Iowa \hfill 2021
  - __Discussant__: Government Transparency in China. Midwest Political Science Association Annual Meeting \hfill Apr 2021
  - __Session Chair and Discussant__:Time and Space. Political Science Methodology Conference for Asia and Australasia \hfill  Jan 2021
  - __Co-Host__: [*2020 Iowa Caucus Conference*](https://clas.uiowa.edu/polisci/Shambaugh-2020Caucus). University of Iowa \hfill Feb 2020
  - __Session Chair__: Understanding Polarization, COVID & Computation and Social Media & Politics.
Politics and Computational Social Science and Political Networks \hfill Aug 2020
  - __Discussant__: Chinese Politics. Southern Political Science Association Conference \hfill Jan 2020

# AWARDS & HONORS
* Nominated to Global Student Awards, University of Iowa \hfill Fall 2021
* Finalist for annual “Thesis Challenge,” University of Iowa  \hfill Fall 2021
* Graduate Post-Comp Research Fellowship ($10,500), University of Iowa \hfill Fall 2021
* Graduate College Summer Fellowship ($5,000), University of Iowa  \hfill Summer 2021
* Department Research Grant ($1,000), University of Iowa  \hfill Spring 2020
* GSS Travel Funds ($1,000), University of Iowa  \hfill Spring 2020
* Department Research Grant ($300), University of Iowa   \hfill Spring 2019 
* Center for Asian and Pacific Studies Graduate Travel Grant ($500), University of Iowa \hfill Fall 2019
* Department Summer Training Grant ($2400), University of Iowa \hfill Summer 2018

# ADDITIONAL TRAINING AND SKILLS
* __Certificate__
  - Certificate in Informatics, The University of Iowa, U.S.A. \hfill 2021
    - Programming in Python, Java, and SQL.
  - ICPSR, University of Michigan, Ann Arbor, MI  \hfill 2018
    - Causal Inference for the Social Sciences & Multilevel Models II: Advanced Topics.
    
* __Skills__
  - Analysis & Programming: R, Python, SQL, Stata, Stan, JAGS,  Mplus, Java.
  - Application:  LaTeX, Markdown, Git(GitHub).
  - Language: English, Chinese (Mandarin)


# REFERENCES
* __Frederick Solt__, __Ph.D__ \hfill __Bruce A. Desmarais__, __Ph.D__
* frederick-solt@uiowa.edu; (319)335-2340 \hfill  bdesmarais@psu.edu; (814) 863-1595,
* Professor, University of Iowa \hfill  Professor, Penn State University
* __Xun Cao__, __Ph.D__ \hfill __Bryce Dietrich__, __Ph.D__
* xuc11@psu.edu; (814) 865-8749 \hfill  bjdietri@purdue.edu; (765) 494-4161
* Professor, Penn State University \hfill Associate Professor, Purdue University
* __Elizabeth J. Menninga__, __Ph.D__
* elizabeth-menninga@uiowa.edu; (319) 335-3835
* Associate Professor, University of Iowa

